### ISSUE TITLE
DatedPrice Issue

### ISSUE THREAD

**Issue by floatingheads** [beancount/beanprice#104]
There seems to be an issue with DatedPrice. When I try to get the price manually at a specific date for a commodity, I get this error.

bean-price -e USD:yahoo/ETH-USD --date 2025-04-03

ERROR   : Error fetching ETH-USD: Expecting value: line 1 column 1 (char 0)
ERROR   : Could not fetch for job: DatedPrice(base='ETH-USD', quote='USD', date=datetime.date(2025, 4, 3), sources=[PriceSource(module=<module 'beanprice.sources.yahoo' from 'MyPath\\Python311\\site-packages\\beanprice\\sources\\yahoo.py'>, symbol='ETH-USD', invert=False)])

Noticed this initially when using --update for my Beancount file.

**Comment by Nexus2k** [comment]
See https://query1.finance.yahoo.com/v7/finance/quote looks like Yahoo locked down the price API :(

**Comment by Nexus2k** [comment]
Found a fix for it: if you apply https://github.com/beancount/beanprice/pull/86/files but change fc.yahoo.com to finance.yahoo.com you can get the quotes 👯‍♀

**Comment by floatingheads** [comment]
@Nexus2k that doesn't work for me, unfortunately. I get the exact same error.

Also, to be clear, if I don't use a specific date, then it works just fine. For instance,

bean-price -e USD:yahoo/ETH-USD

works as expected.

**Comment by cainau** [comment]
I think this may have already been fixed by https://github.com/beancount/beanprice/commit/9aa7c5eaa7560add9a58b4dc9ee3443c4653e42d

But that commit came after the most recent release.

**Comment by floatingheads** [comment]
@cainau that worked! Thank you!

**Comment by sabaimran** [comment]
I'm actually still getting this error. Just installed from master, and I'm getting this error:

```bash
bean-price -e USD:yahoo/VOO
ERROR   : Error fetching VOO: Expecting value: line 1 column 1 (char 0)
ERROR   : Could not fetch for job: DatedPrice(base='VOO', quote='USD', date=None, sources=[PriceSource(module=<module 'beanprice.sources.yahoo' from '/Users/si/projects/beancount/.venv/lib/python3.12/site-packages/beanprice/sources/yahoo.py'>, symbol='VOO', invert=False)])
```

Not sure why. My coinbase references seem to be working fine though, so seems like a Yahoo-specific issue?
